USE [DbAlliance]
GO

/****** Object:  Table [dbo].[USUARIOS]    Script Date: 13/12/2021 14:15:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--DROP TABLE [dbo].[USUARIOS]


CREATE TABLE [dbo].[USUARIOS](
	id       INT IDENTITY(1,1) NOT NULL
	,CLAN    INT NOT NULL
	,CLASSE  INT NOT NULL
	,DISCORD NVARCHAR(255) NOT NULL
	,EMAIL   NVARCHAR(255) NOT NULL
	,FONE	 NVARCHAR(255) NOT NULL
	,NICK    NVARCHAR(255) NOT NULL
	,NICK2   NVARCHAR(255) NOT NULL
	,NIVEL   INT NOT NULL
	,PODER   INT NOT NULL
	,STATUS  INT NOT NULL
	,DATA    DATETIME
PRIMARY KEY CLUSTERED 
(
	id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


